export const sidebarLocators = {
    // Locators adhering to Playwright best practices
    menuMarketing: 'Marketing', // For getByText or getByRole
    menuBannerManagement: 'Banner Management',
    menuBannerConfig: 'Banner Config',
    menuBannerOrdering: 'Banner Ordering',
    menuTutorial: 'Tutorials',
    menuTutorialConfig: 'Tutorial Configuration',
    menuCompensation: 'Compensation',
    menuCouponManagement: 'Coupon Management',
    menuCampaign: 'Campaign',
    menuCashbackPromotions: 'Cashback Promotions',
    menuEventCalendar: 'Event Calender',
    menuFanExclusive: 'Fan Exclusive',
    menuPlatform: 'Platform',
    menuFormBuilderConfiguration: 'Form Builder Configuration',
    menuFormBuilder: 'Form Builder',
    menuLeaderboard: 'Leaderboard',
    menuLoyaltyPromotions: 'Loyalty Promotions',
    menuSegmentSchedule: 'Segment Schedule',
    menuSegmentation: 'Segmentation',
    menuTelegramLeaderboard: 'Telegram Leaderboard',
    menuToastConfig: 'Toast Configuration',
    menuPromotions: 'Promotions',
    menuGenericWheel: 'Generic Wheel',
    menuSystemAdmin: 'System Admin',
    menuInternalNotification: 'Internal Notifications',
    menuPromotionConfig: 'Promotion Config',
    menuPromotionOrdering: 'Promotions Ordering',
    menuScratchAndWin: 'Scratch and Win',
    menuTimedPromotions: 'Timed Promotions',
    menuTagManagement: 'Tag Management',
    menuPlayerTagging: 'Player Tagging',
    menuPlayerTaggingLogs: 'Player Tagging Logs',
    menuSegmentTagging: 'Segment Tagging',
    menuTagConfig: 'Tag Configuration',
    menuTutorialOrdering: 'Tutorial Ordering',
    menuMarketingComps: 'Marketing Comps',
    menuCompAlerts: 'Comp Alerts',
    menuCompsBulk: 'Comp Bulk',
    // The app used to render this as "Comp Managament" (its own typo) — since
    // fixed on their end, the sidebar now genuinely reads "Comp Config".
    menuCompConfig: 'Comp Config',
    menuManualComps: 'Manual Comps',
    menuTransactionTypes: 'Transaction Types',
    menuWhitelistTestAccounts: 'Whitelist Test Accounts',
    menuNotificationManagement: 'Notification Management',
    menuAdminAccounts: 'Admin Accounts',
    menuMessageCategories: 'Message Categories',
    menuMessageCTA: "Message CTA's",
    menuMessageTemplates: 'Message Templates',
    menuNotificationSchedule: 'Notification Schedule',
    menuFormBuilderConfig: 'Form Builder Configuration',
    menuStencilConfig: 'Stencil Configuration',
};